[package]
name = "systemd-udp-proxy"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
listenfd = "1.0"
log = "0.4"
tokio = { version = "1.38", features = ["io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
